version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-slides_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-slides_pass}
      POSTGRES_DB: ${POSTGRES_DB:-slides_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql+psycopg2://slides_user:slides_pass@postgres:5432/slides_db}
      - SLIDE_STORAGE_PATH=${SLIDE_STORAGE_PATH:-/data/slides}
    volumes:
      - slides_data:/data/slides
      - ./backend:/app
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-/api}
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
  slides_data:
